### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jesush**
Added detailed build instructions, and information on how to go about building it under a MacOSX environment.

### CODE REVIEW

**Comment by johannesbreyer** [comment]
hello,
I have a question regarding your tool, yet can’t seem to find your email address.
what is the best way to get in touch with you?
many thanks!
JB

**Comment by jesush** [comment]
Sure thing,

You can contact via email at the address below. 

What's your question?

Best Regards,
Jesus H
jshernandez3@uh.edu

**Comment by jesush** [comment]
Sure thing,

You can contact via email, I just sent you one.

Best Regards,
Jesus H

**Comment by dmishin** [comment]
Hello, and thank you!

Wow, I am really happy that somebody found my tool useful. I've added you to the collaborators list, so you probably can push directly.
You can contact me via shintyakov at gmail.com, or using github facilities.

Don't hesitate to ask me anything.

**Pull request merged**
